apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zlzookeeper
  labels:
    app: zlzookeeper
spec:
  serviceName: zk-hs
  replicas: 3
  selector:
    matchLabels:
      app: zlzookeeper
  template:
    metadata:
      labels:
        app: zlzookeeper
    spec:
      serviceAccountName: zlapp-sa
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: zlzookeeper
          image: <YOUR-ACCOUNT-ID>.dkr.ecr.us-east-1.amazonaws.com/ue1-zlps-ecr-01:zlzookeeper20251219
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: zlapp-config
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: peer
            - containerPort: 3888
              name: election
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 500Mi
          volumeMounts:
            - name: zlzkdata
              mountPath: /var/ZipLip/DATA/ZooKeeper
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: zlzkdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
        storageClassName: ebs-sc