apiVersion: v1
kind: Service
metadata:
  name: zlui       
  labels:
    app: zlui
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      protocol: "TCP"
      targetPort: 80
    - name: "8000"
      port: 8000
      protocol: "TCP"
      targetPort: 8000
    - name: "9975"
      port: 9975
      protocol: "FileConnector"
      targetPort: 9975
    - name: "9970"
      port: 9970
      protocol: "Sharepoint"
      targetPort: 9970
  selector:
    app: zlui
