apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-zlvault
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0a4ec87cd91178047::fsap-070de74811e8c461f
