apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-archive
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-pv-archive
    volumeAttributes:
      bucketName: usw1-zlps-app-storage
