apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-archive-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: s3-pv-archive
