apiVersion: v1
kind: ConfigMap
metadata:
  name: zlapp-config  
  namespace: default
data:
  # ZOO_SERVERS removed - using zkQuorum.cfg from zkclient-config ConfigMap
  TIKA_HOST: zltika
  TIKA_PORT: "9972"
  __tika.ZLTikaService.Host: zltika
  __tika.ZLTikaService.Port: "9972"
  DEFAULT_URL: ps/PmApp/zlp_dummy?mgc=1\&NextPage=/app/home.jsp\&domain=yourdomain.com\&la=en\&authMethod=ZipLipDB\&resId=trac_login