DROP SEQUENCE pfuser.RecategorizationTask_seq
DROP TABLE pfuser.RecategorizationTask
DROP TABLE pfuser.InPlaceStaticTagLexiconMap
DROP TABLE pfuser.UserGeoTags
DROP SEQUENCE pfuser.InPlaceTagStats_sequence
DROP TABLE pfuser.InPlaceTagStats
DROP TABLE pfuser.InPlaceIngestDisposeStats
DROP SEQUENCE pfuser.InPlaceFolderStats_sequence
DROP TABLE pfuser.InPlaceFolderStats
DROP TABLE pfuser.InPlaceFileItemStaticTag
DROP SEQUENCE pfuser.InPlaceTag_seq
DROP TABLE pfuser.InPlaceTag
DROP TABLE pfuser.InPlaceFileScheduledRuns
DROP SEQUENCE pfuser.InPlaceFileDispRuns_sequence
DROP TABLE pfuser.InPlaceFileDispositionRuns
DROP TABLE pfuser.InPlaceFileAuditTrail
DROP SEQUENCE pfuser.InPlaceFileItem_sequence
DROP TABLE pfuser.InPlaceFileItem
DROP TABLE pfuser.StorageItemLink
-- OPTIONAL
DROP SEQUENCE pfuser.StorItemRelationship_sequence
DROP TABLE pfuser.StorageItemRelationship
DROP TABLE pfuser.StorageItemStats
DROP TABLE pfuser.FileSingleInstanceDigest
DROP TABLE pfuser.StorageViolation
DROP SEQUENCE pfuser.StorViolTranscript_sequence
DROP TABLE pfuser.StorageViolationTranscript
DROP TABLE pfuser.StorageUserSubscription
DROP TABLE pfuser.StorageAuditTrail
DROP TABLE pfuser.StorageItemPart
DROP TABLE pfuser.StorageItemSisHeader
DROP SEQUENCE pfuser.StorageItemVersion_sequence
DROP TABLE pfuser.StorageItemVersion
DROP SEQUENCE pfuser.StorageItem_sequence
DROP TABLE pfuser.StorageItem
DROP TABLE pfuser.StorageFolderProp
DROP SEQUENCE pfuser.StorageFolder_sequence
DROP TABLE pfuser.StorageFolder
DROP TABLE pfuser.StorageProjectPrivileges
-- OPTIONAL
DROP SEQUENCE pfuser.StorageProject_sequence
DROP TABLE pfuser.StorageProject
