module.exports = {
  authService: require('./authService'),
  credentialService: require('./credentialService'),
  deploymentService: require('./deploymentService'),
  awsService: require('./awsService'),
  logger: require('./logger'),
  logService: require('./logService'),
  metricsCollector: require('./metricsCollector'),
  alertService: require('./alertService'),
  secureAlertService: require('./secureAlertService'),
  secureCredentialService: require('./secureCredentialService'),
  deploymentTemplateService: require('./deploymentTemplateService'),
  costOptimizationService: require('./costOptimizationService'),
  costEstimationService: require('./costEstimationService'),
  multiCloudOrchestrator: require('./multiCloudOrchestrator'),
  terraformExecutor: require('./terraformExecutor'),
  websocketEmissionService: require('./websocketEmissionService'),
  transactionHelper: require('./transactionHelper'),
  databaseScriptExecutor: require('./databaseScriptExecutor'),
  infrastructureDiscovery: require('./infrastructureDiscovery'),
  databaseCredentialService: require('./databaseCredentialService'),
  KubernetesManifestGenerator: require('./kubernetesManifestGenerator'),
  ZLManifestTemplates: require('./zlManifestTemplates'),
  zlDeploymentOrchestrator: require('./zlDeploymentOrchestrator'),
  ldapService: require('./ldapService'),
  adConfigService: require('./adConfigService'),
  auditService: require('./auditService'),
};
