DROP SEQUENCE pfuser.FileTag_Sequence
DROP TABLE pfuser.FileTag
DROP TABLE pfuser.FileTagAction
DROP SEQUENCE pfuser.FileTreeDataCollect_sequence
DROP TABLE pfuser.FileTreeDataCollect
DROP SEQUENCE pfuser.FileTreeSearch_sequence
DROP TABLE pfuser.FileTreeSearch
DROP TABLE pfuser.FileTreeEntry
DROP TABLE pfuser.FileTreePrivileges
DROP TABLE pfuser.FileTreeRemediation
DROP SEQUENCE pfuser.FTRemediationRuns_seq
DROP TABLE pfuser.FileTreeRemediationRuns
DROP SEQUENCE pfuser.FileTreeDashboard_seq
DROP TABLE pfuser.FileTreeDashboard
DROP TABLE pfuser.FileTreeAuditTrail
DROP TABLE pfuser.FileTreeScheduledRuns
DROP SEQUENCE pfuser.FTDispositionRuns_sequence
DROP TABLE pfuser.FileTreeDispositionRuns
DROP TABLE pfuser.FileTreeEntrySyncAction
