TRUNCATE TABLE pfuser01.ZLInstance
TRUNCATE TABLE pfuser01.Tenant
TRUNCATE TABLE pfuser01.ZipAccount
TRUNCATE TABLE pfuser01.DomainInfo
TRUNCATE TABLE pfuser01.UserSession
TRUNCATE TABLE pfuser01.AppLifeCycle
TRUNCATE TABLE pfuser01.ParameterSet
TRUNCATE TABLE pfuser01.ParameterElement
TRUNCATE TABLE pfuser01.EventLog
TRUNCATE TABLE pfuser01.SystemAudit
TRUNCATE TABLE pfuser01.ProtectedKey
TRUNCATE TABLE pfuser01.UserAuthentication
TRUNCATE TABLE pfuser01.UserRoles
TRUNCATE TABLE pfuser01.SystemLock
TRUNCATE TABLE pfuser01.ZLPolicy
TRUNCATE TABLE pfuser01.ZLPolicyRule
TRUNCATE TABLE pfuser01.EntityObject
TRUNCATE TABLE pfuser01.ZLObject
TRUNCATE TABLE pfuser01.RetentionPeriod
TRUNCATE TABLE pfuser01.PmTag
TRUNCATE TABLE pfuser01.ZLTempParam
TRUNCATE TABLE pfuser01.UserSearch
TRUNCATE TABLE pfuser01.SavedUserSearch
TRUNCATE TABLE pfuser01.LegalHold
TRUNCATE TABLE pfuser01.Site
TRUNCATE TABLE pfuser01.SiteMachine
TRUNCATE TABLE pfuser01.WorkflowTask
TRUNCATE TABLE pfuser01.OAuthConsumer
TRUNCATE TABLE pfuser01.OAuthAccessor
TRUNCATE TABLE pfuser01.TLSCertificate
TRUNCATE TABLE pfuser01.CloudCredentials
TRUNCATE TABLE pfuser01.ZLNotifyEvent
TRUNCATE TABLE pfuser01.ZLNotifyMessage
TRUNCATE TABLE pfuser01.UserSchema
TRUNCATE TABLE pfuser01.UserSchemaFields
TRUNCATE TABLE pfuser01.NamedLegalHold
TRUNCATE TABLE pfuser01.NamedLegalHoldPrivileges
TRUNCATE TABLE pfuser01.Label
TRUNCATE TABLE pfuser01.LabelItem
TRUNCATE TABLE pfuser01.ApprovalRequest
TRUNCATE TABLE pfuser01.Approval
TRUNCATE TABLE pfuser01.EscalationChain
TRUNCATE TABLE pfuser01.EscalationEntry
TRUNCATE TABLE pfuser01.RetentionPeriodPrivileges
TRUNCATE TABLE pfuser01.RestrictedSearchRequest
TRUNCATE TABLE pfuser01.ShortUrl
TRUNCATE TABLE pfuser01.SystemRepeat
TRUNCATE TABLE pfuser01.TQueue
TRUNCATE TABLE pfuser01.TQueueMsg
TRUNCATE TABLE pfuser01.TQueueObject
TRUNCATE TABLE pfuser01.UserActivity
TRUNCATE TABLE pfuser01.UserRVite
TRUNCATE TABLE pfuser01.RetentionProcess
TRUNCATE TABLE pfuser01.RetentionProcessHistory
TRUNCATE TABLE pfuser01.RetentionTask
TRUNCATE TABLE pfuser01.PurgeDoc
TRUNCATE TABLE pfuser01.UserTagContext

