apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zlzookeeper
  labels:
    app: zlzookeeper
spec:
  serviceName: zk-hs
  replicas: 3
  selector:
    matchLabels:
      app: zlzookeeper
  template:
    metadata:
      labels:
        app: zlzookeeper
    spec:
      serviceAccountName: zlapp-sa
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: zlzookeeper
          image: 995553364920.dkr.ecr.us-east-1.amazonaws.com/ue1-zlps-ecr-01:zlzookeeper20251219
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: zlapp-config
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: peer
            - containerPort: 3888
              name: election
          volumeMounts:
            - name: zk-config
              mountPath: /opt/ZipLip/ZLZooKeeper/config
            - name: zlzkdata
              mountPath: /var/ZipLip/DATA/ZooKeeper
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 500Mi
      initContainers:
        - name: setup-config
          image: busybox
          command:
            - sh
            - -c
            - echo $(hostname) > /var/ZipLip/DATA/ZooKeeper/myid
          volumeMounts:
            - name: zlzkdata
              mountPath: /var/ZipLip/DATA/ZooKeeper
      volumes:
        - name: zk-config
          configMap:
            name: zk-config
  volumeClaimTemplates:
    - metadata:
        name: zlzkdata
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: efs-sc
        resources:
          requests:
            storage: 10Gi