apiVersion: v1
data:
  DB_HOST: use1-zlps-msexpsql-01-eks.cqhaqqqiwngv.us-east-1.rds.amazonaws.com
  DB_NAME: zldb
  DB_PORT: "1433"
  DB_TYPE: mssql
  DB_USER: pfuser
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DB_HOST":"usw1-zlps-msexpsql-01-eks.c5s06occm2dn.us-west-1.rds.amazonaws.com","DB_NAME":"zldb","DB_PORT":"1433","DB_TYPE":"mssql","DB_USER":"pfuser"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"db-config","namespace":"default"}}
  creationTimestamp: "2025-12-17T17:42:32Z"
  name: db-config
  namespace: default
  resourceVersion: "2106808"
  uid: 6983d29f-da4c-4e50-9b0a-9bbbbcf201ce
