apiVersion: v1
data:
  DB_PASSWORD: TEpaLXdrVnZAdF8hZCpQaU0ydGJ4M1RaNGg=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DB_PASSWORD":"TEpaLXdrVnZAdF8hZCpQaU0ydGJ4M1RaNGg="},"kind":"Secret","metadata":{"annotations":{},"name":"db-secret","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2025-12-17T17:42:40Z"
  name: db-secret
  namespace: default
  resourceVersion: "476185"
  uid: f66adec1-871e-4a59-b25c-46426245a141
type: Opaque
