TRUNCATE TABLE pfuser.ZLInstance
TRUNCATE TABLE pfuser.Tenant
TRUNCATE TABLE pfuser.ZipAccount
TRUNCATE TABLE pfuser.DomainInfo
TRUNCATE TABLE pfuser.UserSession
TRUNCATE TABLE pfuser.AppLifeCycle
TRUNCATE TABLE pfuser.ParameterSet
TRUNCATE TABLE pfuser.ParameterElement
TRUNCATE TABLE pfuser.EventLog
TRUNCATE TABLE pfuser.SystemAudit
TRUNCATE TABLE pfuser.ProtectedKey
TRUNCATE TABLE pfuser.UserAuthentication
TRUNCATE TABLE pfuser.UserRoles
TRUNCATE TABLE pfuser.SystemLock
TRUNCATE TABLE pfuser.ZLPolicy
TRUNCATE TABLE pfuser.ZLPolicyRule
TRUNCATE TABLE pfuser.EntityObject
TRUNCATE TABLE pfuser.ZLObject
TRUNCATE TABLE pfuser.RetentionPeriod
TRUNCATE TABLE pfuser.PmTag
TRUNCATE TABLE pfuser.ZLTempParam
TRUNCATE TABLE pfuser.UserSearch
TRUNCATE TABLE pfuser.SavedUserSearch
TRUNCATE TABLE pfuser.LegalHold
TRUNCATE TABLE pfuser.Site
TRUNCATE TABLE pfuser.SiteMachine
TRUNCATE TABLE pfuser.WorkflowTask
TRUNCATE TABLE pfuser.OAuthConsumer
TRUNCATE TABLE pfuser.OAuthAccessor
TRUNCATE TABLE pfuser.TLSCertificate
TRUNCATE TABLE pfuser.CloudCredentials
TRUNCATE TABLE pfuser.ZLNotifyEvent
TRUNCATE TABLE pfuser.ZLNotifyMessage
TRUNCATE TABLE pfuser.UserSchema
TRUNCATE TABLE pfuser.UserSchemaFields
TRUNCATE TABLE pfuser.NamedLegalHold
TRUNCATE TABLE pfuser.NamedLegalHoldPrivileges
TRUNCATE TABLE pfuser.Label
TRUNCATE TABLE pfuser.LabelItem
TRUNCATE TABLE pfuser.ApprovalRequest
TRUNCATE TABLE pfuser.Approval
TRUNCATE TABLE pfuser.EscalationChain
TRUNCATE TABLE pfuser.EscalationEntry
TRUNCATE TABLE pfuser.RetentionPeriodPrivileges
TRUNCATE TABLE pfuser.RestrictedSearchRequest
TRUNCATE TABLE pfuser.ShortUrl
TRUNCATE TABLE pfuser.SystemRepeat
TRUNCATE TABLE pfuser.TQueue
TRUNCATE TABLE pfuser.TQueueMsg
TRUNCATE TABLE pfuser.TQueueObject
TRUNCATE TABLE pfuser.UserActivity
TRUNCATE TABLE pfuser.UserRVite
TRUNCATE TABLE pfuser.RetentionProcess
TRUNCATE TABLE pfuser.RetentionProcessHistory
TRUNCATE TABLE pfuser.RetentionTask
TRUNCATE TABLE pfuser.PurgeDoc
TRUNCATE TABLE pfuser.UserTagContext
