TRUNCATE TABLE pfuser.RecordStore
TRUNCATE TABLE pfuser.SupplementalMarkings
TRUNCATE TABLE pfuser.FilePlan
TRUNCATE TABLE pfuser.Record
TRUNCATE TABLE pfuser.RecordAuditTrail
TRUNCATE TABLE pfuser.RecordUserData
TRUNCATE TABLE pfuser.RecordDataSource
TRUNCATE TABLE pfuser.RecordDataSourceRuns
TRUNCATE TABLE pfuser.RecordDataSourceScheduledRuns
TRUNCATE TABLE pfuser.RecordSchema
TRUNCATE TABLE pfuser.RecordSchemaFields
TRUNCATE TABLE pfuser.RetentionCode
TRUNCATE TABLE pfuser.LifeCycleRun
TRUNCATE TABLE pfuser.LifeCycleRunEntry
TRUNCATE TABLE pfuser.FilePlanPrivileges
TRUNCATE TABLE pfuser.FilePlanCustomPrivileges
TRUNCATE TABLE pfuser.EntityMarking
TRUNCATE TABLE pfuser.UserRecordDeclaration
TRUNCATE TABLE pfuser.FieldValueFilter
TRUNCATE TABLE pfuser.RecordRelationship
TRUNCATE TABLE pfuser.RecordLink
TRUNCATE TABLE pfuser.CategoryDispositionRun
TRUNCATE TABLE pfuser.CategoryDispositionTransaction
TRUNCATE TABLE pfuser.RecordUserPreference
TRUNCATE TABLE pfuser.LifeCyclePhase
TRUNCATE TABLE pfuser.DispositionAuthority
TRUNCATE TABLE pfuser.FilePlanFavorite
TRUNCATE TABLE pfuser.RecordSavedSearch
TRUNCATE TABLE pfuser.EntityClearance
TRUNCATE TABLE pfuser.ClassificationGuide
TRUNCATE TABLE pfuser.ClassifiedReason
TRUNCATE TABLE pfuser.ClassificationRule
