DROP SEQUENCE pfuser.CustodianLegalHold_sequence
DROP TABLE pfuser.CustodianLegalHold
DROP SEQUENCE pfuser.CaseTag_sequence
DROP TABLE pfuser.CaseTag
DROP TABLE pfuser.CustodianAlias
DROP SEQUENCE pfuser.Custodian_sequence
DROP TABLE pfuser.Custodian
DROP TABLE pfuser.CaseAuditTrail
DROP TABLE pfuser.CaseItemProperty
DROP TABLE pfuser.CaseItem
DROP TABLE pfuser.CasePrivileges
DROP TABLE pfuser.CaseUserPreference
DROP TABLE pfuser.CaseUserSubscription
DROP SEQUENCE pfuser.CaseDataSourceRuns_sequence
DROP TABLE pfuser.CaseDataSourceRuns
DROP TABLE pfuser.CaseDataSourceScheduledRuns
-- OPTIONAL
DROP SEQUENCE pfuser.CaseDataSource_sequence
DROP TABLE pfuser.CaseDataSource
DROP SEQUENCE pfuser.Case_sequence
DROP TABLE pfuser.CaseInfo
DROP SEQUENCE pfuser.SurveyForm_sequence
DROP TABLE pfuser.SurveyForm
DROP SEQUENCE pfuser.SurveyFormVersion_sequence
DROP TABLE pfuser.SurveyFormVersion
DROP TABLE pfuser.SurveyFormObject
DROP TABLE pfuser.CustodianSurvey
DROP TABLE pfuser.CustodianSurveyAnswers
DROP TABLE pfuser.CustodianSurveyAction
DROP TABLE pfuser.CaseRedaction
DROP SEQUENCE pfuser.CaseTask_seq
DROP TABLE pfuser.CaseTask
DROP SEQUENCE pfuser.ZlCaseObject_sequence
DROP TABLE pfuser.ZlCaseObject
DROP TABLE pfuser.CaseTaskEntity
DROP SEQUENCE pfuser.CaseTaskAnnot_seq
DROP TABLE pfuser.CaseTaskAnnotation
DROP SEQUENCE pfuser.InvRequest_sequence
DROP TABLE pfuser.InvestigationRequest
DROP SEQUENCE pfuser.CaseTaskAuditTrail_sequence
DROP TABLE pfuser.CaseTaskAuditTrail
-- OPTIONAL
DROP SEQUENCE pfuser.CaseSchema_sequence
DROP TABLE pfuser.CaseSchema
DROP TABLE pfuser.CaseSchemaFields
DROP SEQUENCE pfuser.CaseUserData_sequence
DROP TABLE pfuser.CaseUserData
-- OPTIONAL
DROP SEQUENCE pfuser.ReviewPhase_sequence
DROP TABLE pfuser.ReviewPhase
-- OPTIONAL
DROP SEQUENCE pfuser.ReviewBucket_sequence
DROP TABLE pfuser.ReviewBucket
DROP TABLE pfuser.ReviewBucketItem
DROP SEQUENCE pfuser.RevBucImpRuns_sequence
DROP TABLE pfuser.ReviewBucketImportRun
DROP TABLE pfuser.CaseReviewer
DROP TABLE pfuser.ConceptWordList
DROP SEQUENCE pfuser.CustCollect_sequence
DROP TABLE pfuser.CustodianCollection
DROP TABLE pfuser.CustCollPackage
DROP TABLE pfuser.CcPackageAttach
DROP SEQUENCE pfuser.CustCollectionRun_sequence
DROP TABLE pfuser.CustodianCollectionRun
DROP TABLE pfuser.GlobalCustodian
DROP TABLE pfuser.GlobalCustodianAlias
DROP TABLE pfuser.CaseExport
DROP SEQUENCE pfuser.CaseSearch_sequence
DROP TABLE pfuser.CaseSearch
DROP TABLE pfuser.FedDocumentTransport
DROP TABLE pfuser.CaseInPlaceItem
