TRUNCATE TABLE pfuser.CustodianLegalHold
TRUNCATE TABLE pfuser.CaseTag
TRUNCATE TABLE pfuser.CustodianAlias
TRUNCATE TABLE pfuser.Custodian
TRUNCATE TABLE pfuser.CaseAuditTrail
TRUNCATE TABLE pfuser.CaseItemProperty
TRUNCATE TABLE pfuser.CaseItem
TRUNCATE TABLE pfuser.CasePrivileges
TRUNCATE TABLE pfuser.CaseUserPreference
TRUNCATE TABLE pfuser.CaseUserSubscription
TRUNCATE TABLE pfuser.CaseDataSourceRuns
TRUNCATE TABLE pfuser.CaseDataSourceScheduledRuns
TRUNCATE TABLE pfuser.CaseDataSource
TRUNCATE TABLE pfuser.CaseInfo
TRUNCATE TABLE pfuser.SurveyForm
TRUNCATE TABLE pfuser.SurveyFormVersion
TRUNCATE TABLE pfuser.SurveyFormObject
TRUNCATE TABLE pfuser.CustodianSurvey
TRUNCATE TABLE pfuser.CustodianSurveyAnswers
TRUNCATE TABLE pfuser.CustodianSurveyAction
TRUNCATE TABLE pfuser.CaseRedaction
TRUNCATE TABLE pfuser.CaseTask
TRUNCATE TABLE pfuser.ZlCaseObject
TRUNCATE TABLE pfuser.CaseTaskEntity
TRUNCATE TABLE pfuser.CaseTaskAnnotation
TRUNCATE TABLE pfuser.InvestigationRequest
TRUNCATE TABLE pfuser.CaseTaskAuditTrail
TRUNCATE TABLE pfuser.CaseSchema
TRUNCATE TABLE pfuser.CaseSchemaFields
TRUNCATE TABLE pfuser.CaseUserData
TRUNCATE TABLE pfuser.ReviewPhase
TRUNCATE TABLE pfuser.ReviewBucket
TRUNCATE TABLE pfuser.ReviewBucketItem
TRUNCATE TABLE pfuser.ReviewBucketImportRun
TRUNCATE TABLE pfuser.CaseReviewer
TRUNCATE TABLE pfuser.ConceptWordList
TRUNCATE TABLE pfuser.CustodianCollection
TRUNCATE TABLE pfuser.CustCollPackage
TRUNCATE TABLE pfuser.CcPackageAttach
TRUNCATE TABLE pfuser.CustodianCollectionRun
TRUNCATE TABLE pfuser.GlobalCustodian
TRUNCATE TABLE pfuser.GlobalCustodianAlias
TRUNCATE TABLE pfuser.CaseExport
TRUNCATE TABLE pfuser.CaseSearch
TRUNCATE TABLE pfuser.FedDocumentTransport
TRUNCATE TABLE pfuser.CaseInPlaceItem

