TRUNCATE TABLE pfuser.TextItemRetry
TRUNCATE TABLE pfuser.BigDBParam
TRUNCATE TABLE pfuser.BigDBSpace
TRUNCATE TABLE pfuser.BigDBStore
TRUNCATE TABLE pfuser.SearchEngineLoad
TRUNCATE TABLE pfuser.IndexDocRetry
TRUNCATE TABLE pfuser.SearchPartition
TRUNCATE TABLE pfuser.SegmentMergeJob
TRUNCATE TABLE pfuser.SegmentMergeDetails
TRUNCATE TABLE pfuser.InstanceSnapshotSegments
TRUNCATE TABLE pfuser.InstanceSnapshot
TRUNCATE TABLE pfuser.InstanceMergeDetails
TRUNCATE TABLE pfuser.InstanceDataFiles
TRUNCATE TABLE pfuser.IndexDocDelete
TRUNCATE TABLE pfuser.SearchStoreInstance
TRUNCATE TABLE pfuser.SearchStore
TRUNCATE TABLE pfuser.FederationSecurity
TRUNCATE TABLE pfuser.EntitySearchStore
TRUNCATE TABLE pfuser.RemoteSearchHost
