apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    spec:
      containers:
      - name: init
        image: mcr.microsoft.com/mssql-tools:latest
        command: ["/opt/mssql-tools/bin/sqlcmd"]
        args: ["-S", "mssql-service", "-U", "sa", "-P", "YourStrong!Passw0rd", "-d", "zldb", "-i", "/tmp/init-auth.sql"]
        volumeMounts:
        - name: sql-script
          mountPath: /tmp
      volumes:
      - name: sql-script
        configMap:
          name: init-sql
      restartPolicy: Never