apiVersion: v1
data:
  zk.cfg: |-
    tickTime=2000
    initLimit=10
    syncLimit=5
    dataDir=/var/ZipLip/DATA/ZooKeeper
    clientPort=2181
    server.zlzookeeper-0=zlzookeeper-0.zk-hs.default.svc.cluster.local:2888:3888
    server.zlzookeeper-1=zlzookeeper-1.zk-hs.default.svc.cluster.local:2888:3888
    server.zlzookeeper-2=zlzookeeper-2.zk-hs.default.svc.cluster.local:2888:3888
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=1
    maxClientCnxns=60
    admin.enableServer=false
  zkQuorum.cfg: |-
    server.zlzookeeper-0=zlzookeeper-0.zk-hs.default.svc.cluster.local:2888:3888
    server.zlzookeeper-1=zlzookeeper-1.zk-hs.default.svc.cluster.local:2888:3888
    server.zlzookeeper-2=zlzookeeper-2.zk-hs.default.svc.cluster.local:2888:3888
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-18T15:27:01Z"
  name: zk-config
  namespace: default
  resourceVersion: "1587940"
  uid: f0e5df33-8f1d-41c9-bf2b-f11f2e9d0174
