apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zlservertemp-efs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi