DROP SEQUENCE pfuser01.CustodianLegalHold_sequence
DROP TABLE pfuser01.CustodianLegalHold
DROP SEQUENCE pfuser01.CaseTag_sequence
DROP TABLE pfuser01.CaseTag
DROP TABLE pfuser01.CustodianAlias
DROP SEQUENCE pfuser01.Custodian_sequence
DROP TABLE pfuser01.Custodian
DROP TABLE pfuser01.CaseAuditTrail
DROP TABLE pfuser01.CaseItemProperty
DROP TABLE pfuser01.CaseItem
DROP TABLE pfuser01.CasePrivileges
DROP TABLE pfuser01.CaseUserPreference
DROP TABLE pfuser01.CaseUserSubscription
DROP SEQUENCE pfuser01.CaseDataSourceRuns_sequence
DROP TABLE pfuser01.CaseDataSourceRuns
DROP TABLE pfuser01.CaseDataSourceScheduledRuns
-- OPTIONAL
DROP SEQUENCE pfuser01.CaseDataSource_sequence
DROP TABLE pfuser01.CaseDataSource
DROP SEQUENCE pfuser01.Case_sequence
DROP TABLE pfuser01.CaseInfo
DROP SEQUENCE pfuser01.SurveyForm_sequence
DROP TABLE pfuser01.SurveyForm
DROP SEQUENCE pfuser01.SurveyFormVersion_sequence
DROP TABLE pfuser01.SurveyFormVersion
DROP TABLE pfuser01.SurveyFormObject
DROP TABLE pfuser01.CustodianSurvey
DROP TABLE pfuser01.CustodianSurveyAnswers
DROP TABLE pfuser01.CustodianSurveyAction
DROP TABLE pfuser01.CaseRedaction
DROP SEQUENCE pfuser01.CaseTask_seq
DROP TABLE pfuser01.CaseTask
DROP SEQUENCE pfuser01.ZlCaseObject_sequence
DROP TABLE pfuser01.ZlCaseObject
DROP TABLE pfuser01.CaseTaskEntity
DROP SEQUENCE pfuser01.CaseTaskAnnot_seq
DROP TABLE pfuser01.CaseTaskAnnotation
DROP SEQUENCE pfuser01.InvRequest_sequence
DROP TABLE pfuser01.InvestigationRequest
DROP SEQUENCE pfuser01.CaseTaskAuditTrail_sequence
DROP TABLE pfuser01.CaseTaskAuditTrail
-- OPTIONAL
DROP SEQUENCE pfuser01.CaseSchema_sequence
DROP TABLE pfuser01.CaseSchema
DROP TABLE pfuser01.CaseSchemaFields
DROP SEQUENCE pfuser01.CaseUserData_sequence
DROP TABLE pfuser01.CaseUserData
-- OPTIONAL
DROP SEQUENCE pfuser01.ReviewPhase_sequence
DROP TABLE pfuser01.ReviewPhase
-- OPTIONAL
DROP SEQUENCE pfuser01.ReviewBucket_sequence
DROP TABLE pfuser01.ReviewBucket
DROP TABLE pfuser01.ReviewBucketItem
DROP SEQUENCE pfuser01.RevBucImpRuns_sequence
DROP TABLE pfuser01.ReviewBucketImportRun
DROP TABLE pfuser01.CaseReviewer
DROP TABLE pfuser01.ConceptWordList
DROP SEQUENCE pfuser01.CustCollect_sequence
DROP TABLE pfuser01.CustodianCollection
DROP TABLE pfuser01.CustCollPackage
DROP TABLE pfuser01.CcPackageAttach
DROP SEQUENCE pfuser01.CustCollectionRun_sequence
DROP TABLE pfuser01.CustodianCollectionRun
DROP TABLE pfuser01.GlobalCustodian
DROP TABLE pfuser01.GlobalCustodianAlias
DROP TABLE pfuser01.CaseExport
DROP SEQUENCE pfuser01.CaseSearch_sequence
DROP TABLE pfuser01.CaseSearch
DROP TABLE pfuser01.FedDocumentTransport
DROP TABLE pfuser01.CaseInPlaceItem

