TRUNCATE TABLE pfuser01.CustodianLegalHold
TRUNCATE TABLE pfuser01.CaseTag
TRUNCATE TABLE pfuser01.CustodianAlias
TRUNCATE TABLE pfuser01.Custodian
TRUNCATE TABLE pfuser01.CaseAuditTrail
TRUNCATE TABLE pfuser01.CaseItemProperty
TRUNCATE TABLE pfuser01.CaseItem
TRUNCATE TABLE pfuser01.CasePrivileges
TRUNCATE TABLE pfuser01.CaseUserPreference
TRUNCATE TABLE pfuser01.CaseUserSubscription
TRUNCATE TABLE pfuser01.CaseDataSourceRuns
TRUNCATE TABLE pfuser01.CaseDataSourceScheduledRuns
TRUNCATE TABLE pfuser01.CaseDataSource
TRUNCATE TABLE pfuser01.CaseInfo
TRUNCATE TABLE pfuser01.SurveyForm
TRUNCATE TABLE pfuser01.SurveyFormVersion
TRUNCATE TABLE pfuser01.SurveyFormObject
TRUNCATE TABLE pfuser01.CustodianSurvey
TRUNCATE TABLE pfuser01.CustodianSurveyAnswers
TRUNCATE TABLE pfuser01.CustodianSurveyAction
TRUNCATE TABLE pfuser01.CaseRedaction
TRUNCATE TABLE pfuser01.CaseTask
TRUNCATE TABLE pfuser01.ZlCaseObject
TRUNCATE TABLE pfuser01.CaseTaskEntity
TRUNCATE TABLE pfuser01.CaseTaskAnnotation
TRUNCATE TABLE pfuser01.InvestigationRequest
TRUNCATE TABLE pfuser01.CaseTaskAuditTrail
TRUNCATE TABLE pfuser01.CaseSchema
TRUNCATE TABLE pfuser01.CaseSchemaFields
TRUNCATE TABLE pfuser01.CaseUserData
TRUNCATE TABLE pfuser01.ReviewPhase
TRUNCATE TABLE pfuser01.ReviewBucket
TRUNCATE TABLE pfuser01.ReviewBucketItem
TRUNCATE TABLE pfuser01.ReviewBucketImportRun
TRUNCATE TABLE pfuser01.CaseReviewer
TRUNCATE TABLE pfuser01.ConceptWordList
TRUNCATE TABLE pfuser01.CustodianCollection
TRUNCATE TABLE pfuser01.CustCollPackage
TRUNCATE TABLE pfuser01.CcPackageAttach
TRUNCATE TABLE pfuser01.CustodianCollectionRun
TRUNCATE TABLE pfuser01.GlobalCustodian
TRUNCATE TABLE pfuser01.GlobalCustodianAlias
TRUNCATE TABLE pfuser01.CaseExport
TRUNCATE TABLE pfuser01.CaseSearch
TRUNCATE TABLE pfuser01.FedDocumentTransport
TRUNCATE TABLE pfuser01.CaseInPlaceItem


