apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-config-efs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""   # ← THIS IS CRITICAL
