apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-zlserverlogs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0a2b69e49fe46c1f6::fsap-0185f5e486a7ec28c
