apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-quorum-config
data:
  quorum.cfg: |
    server.0=zlzookeeper-0.zk-hs.default.svc.cluster.local:2888:3888
    server.1=zlzookeeper-1.zk-hs.default.svc.cluster.local:2888:3888
    server.2=zlzookeeper-2.zk-hs.default.svc.cluster.local:2888:3888