kind: ConfigMap
apiVersion: v1
metadata:
  name: db-config
data:
  DB_HOST: "usw1-zlps-msexpsql-01-eks.c5s06occm2dn.us-west-1.rds.amazonaws.com"
  DB_NAME: ZLDB
  DB_PORT: '1433'
  DB_TYPE: mssql
  DB_USER: pfuser